// ─── Database Entities ───

export interface ScannedFolder {
  id: number
  path: string
  recursive: number // 1 = include subfolders, 0 = top-level only
  added_at: string
}

export interface FileEntry {
  id: number
  folder_id: number
  name: string
  extension: string
  path: string
  size: number
  modified_at: string
  created_at: string
  category_id: number | null
  indexed_at: string
}

export interface Category {
  id: number
  name: string
  color: string
}

export interface Tag {
  id: number
  name: string
  color: string
}

export interface FileTag {
  file_id: number
  tag_id: number
}

export interface Favorite {
  id: number
  file_id: number
  added_at: string
}

export interface RecentEntry {
  id: number
  file_id: number
  opened_at: string
}

// ─── UI / Renderer Types ───

export interface FileWithMeta extends FileEntry {
  tags: Tag[]
  category: Category | null
  is_favorite: boolean
}

export type ViewMode = 'grid' | 'list'
export type SortField = 'name' | 'modified_at' | 'size' | 'extension' | 'folder'
export type SortDirection = 'asc' | 'desc'
export type ThemeMode = 'light' | 'dark'

export type SidebarView =
  | { type: 'all' }
  | { type: 'favorites' }
  | { type: 'recent' }
  | { type: 'category'; id: number }
  | { type: 'tag'; id: number }
  | { type: 'folder'; id: number }

export interface FilterState {
  search: string
  extensions: string[]
  sortField: SortField
  sortDirection: SortDirection
  sidebarView: SidebarView
}

// ─── Preview Types ───

export interface ExcelPreviewData {
  type: 'excel'
  sheets: ExcelSheet[]
}

export interface ExcelSheet {
  name: string
  headers: string[]
  rows: string[][]
  totalRows: number
}

export interface WordPreviewData {
  type: 'word'
  html: string
}

export interface PdfPreviewData {
  type: 'pdf'
  pages: { pageNumber: number; text: string }[]
  totalPages: number
}

export interface TextPreviewData {
  type: 'text'
  content: string
  lineCount: number
}

export type PreviewData = ExcelPreviewData | WordPreviewData | PdfPreviewData | TextPreviewData | { type: 'unsupported'; message: string }

// ─── App Tab ───

export type AppTab = 'files' | 'notes' | 'tasks' | 'reminders'

// ─── Notes Domain ───

export interface Note {
  id: number
  /**
   * Stable cross-machine identity used by sync, generated by the database
   * (migration 3). Notes used to be merged on `created_at`, which has
   * one-second resolution — two notes created in the same second shared a merge
   * key and destroyed each other's content on both machines.
   */
  sync_id: string
  title: string
  content: string
  category_id: number | null
  created_at: string
  updated_at: string
}

export interface NoteWithMeta extends Note {
  tags: NoteTag[]
  category: NoteCategory | null
}

export interface NoteCategory {
  id: number
  name: string
  color: string
}

export interface NoteTag {
  id: number
  name: string
  color: string
}

export type NoteSortField = 'title' | 'updated_at' | 'created_at'

export type NoteSidebarView =
  | { type: 'all' }
  | { type: 'category'; id: number }
  | { type: 'tag'; id: number }

export interface NoteFilterState {
  search: string
  sortField: NoteSortField
  sortDirection: SortDirection
  sidebarView: NoteSidebarView
}

// ─── Tasks Domain ───

export type TaskStatus = 'todo' | 'in_progress' | 'done'
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent'
export type TaskViewMode = 'list' | 'board'

export interface Task {
  id: number
  /** Stable cross-machine identity used by sync. See `Note.sync_id`. */
  sync_id: string
  title: string
  description: string
  status: TaskStatus
  priority: TaskPriority
  due_date: string | null
  sort_order: number
  category_id: number | null
  created_at: string
  updated_at: string
}

export interface TaskWithMeta extends Task {
  tags: TaskTag[]
  category: TaskCategory | null
}

export interface TaskCategory {
  id: number
  name: string
  color: string
}

export interface TaskTag {
  id: number
  name: string
  color: string
}

export type TaskSortField = 'title' | 'priority' | 'due_date' | 'created_at' | 'sort_order'

export type TaskSidebarView =
  | { type: 'all' }
  | { type: 'status'; status: TaskStatus }
  | { type: 'priority'; priority: TaskPriority }
  | { type: 'category'; id: number }
  | { type: 'tag'; id: number }

export interface TaskFilterState {
  search: string
  sortField: TaskSortField
  sortDirection: SortDirection
  sidebarView: TaskSidebarView
}

// ─── Reminders Domain ───

/** NULL freq means one-off; these are the repeating shapes. */
export type ReminderFreq = 'daily' | 'weekly' | 'monthly' | 'yearly'

/** The escalation ladder, in order. `intensity` is where a firing STARTS. */
export type ReminderIntensity = 'toast' | 'popup' | 'blackout'

export type ReminderEntityType = 'task' | 'note'

export type ReminderOccurrenceState =
  | 'pending'
  | 'fired'
  | 'snoozed'
  | 'acknowledged'
  | 'missed'
  | 'skipped'

export interface Reminder {
  id: number
  /** Stable cross-machine identity used by sync. Generated by the database. */
  sync_id: string
  title: string
  body: string | null
  entity_type: ReminderEntityType | null
  entity_id: number | null
  /** ISO instant of the first firing; the anchor all recurrence derives from. */
  fire_at: string
  freq: ReminderFreq | null
  interval: number
  /** Weekly only: comma-separated 0-6, 0 = Sunday. */
  byweekday: string | null
  lead_time_min: number
  intensity: ReminderIntensity
  escalate_after_min: number | null
  sound: string | null
  auto_created: number
  enabled: number
  created_at: string
  updated_at: string
}

export interface ReminderOccurrence {
  id: number
  reminder_id: number
  fire_at: string
  state: ReminderOccurrenceState
  current_tier: ReminderIntensity | null
  fired_at: string | null
  acknowledged_at: string | null
  snoozed_until: string | null
  snooze_count: number
}

export interface ReminderWithMeta extends Reminder {
  /** Soonest pending/snoozed occurrence, or null when nothing is scheduled. */
  next_occurrence: ReminderOccurrence | null
  /** A firing (or overdue-unacknowledged) occurrence, if there is one. */
  active_occurrence: ReminderOccurrence | null
  missed_count: number
  /** Title of the linked task/note, when the link still resolves. */
  entity_title: string | null
}

/** Which section of the Reminders tab a reminder belongs in. */
export type ReminderBucket = 'firing' | 'upcoming' | 'missed' | 'disabled'

/**
 * Outcome of "Reset to automatic" — handing a reminder that a timing edit detached
 * back to its task's due date.
 *
 * `message` is present when the reset was refused, and also when it succeeded with
 * a caveat worth saying out loud (the task no longer qualifies, so the reminder is
 * now following it *and* switched off).
 */
export interface ReminderResetResult {
  ok: boolean
  message?: string
  reminder: ReminderWithMeta | null
}

/** Everything the renderer supplies when creating or editing a reminder. */
export interface ReminderInput {
  title: string
  body: string | null
  fire_at: string
  freq: ReminderFreq | null
  interval: number
  byweekday: number[] | null
  lead_time_min: number
  intensity: ReminderIntensity
  escalate_after_min: number | null
  sound: string | null
  entity_type: ReminderEntityType | null
  entity_id: number | null
}

export interface ReminderAlertItem {
  title: string
  fire_at: string
}

/** What an alert window renders. Pushed from main; never derived in the renderer. */
export interface ReminderAlertPayload {
  kind: 'single' | 'digest'
  occurrence_id: number | null
  reminder_id: number | null
  title: string
  body: string | null
  tier: ReminderIntensity
  fire_at: string
  /** Fired late (missed while the app was closed/asleep). */
  late: boolean
  /** How many further firings are waiting behind this one. */
  queued_count: number
  /** Digest contents; empty for a single alert. */
  items: ReminderAlertItem[]
  /** base64 data URI — a file:// path would be blocked by the renderer CSP. */
  sound_data_uri: string | null
  loop_sound: boolean
}

/** Snooze presets offered by the alert window and the Reminders tab. */
export type ReminderSnoozeChoice = 5 | 10 | 30 | 60 | 'tomorrow'

// ─── Window Mode ───

export type WindowMode = 'normal' | 'widget'
export type WidgetState = 'collapsed' | 'expanded'

// ─── Sync ───

export interface SyncConfig {
  enabled: boolean
  syncPath: string
  lastSyncedAt: string | null
  autoSync: boolean
}

/**
 * Why a sync read declined to proceed. `missing` means the share has no payload
 * yet (nothing to lose — safe to seed it); the other two mean we could not read
 * what is there, so writing over it would discard remote-only data.
 */
export type SyncSkipReason = 'missing' | 'unreadable' | 'unreachable'

export interface SyncResult {
  success: boolean
  message: string
  exportedAt?: string
  skipReason?: SyncSkipReason
}

export interface SyncPreferences {
  theme: string
  viewMode: string
  sidebarCollapsed: boolean
  activeTab: string
  /**
   * Reminder behaviour settings (from AppPreferences), synced alongside the UI
   * ones because they *have* to agree between machines.
   *
   * With machine A on a 'high' threshold and machine B on 'urgent', a high
   * priority task made an auto reminder on A and none on B: B's next edit of that
   * task removed the reminder, A's next export re-supplied it, and the two
   * machines fought over it indefinitely. The automation can only be
   * deterministic if its inputs are the same everywhere.
   *
   * OPTIONAL: a payload written before this shipped has none of these keys, and
   * that must mean "leave my settings alone", not "reset them to defaults".
   * Filled in by exportData from the main process's own prefs — the renderer does
   * not own them.
   */
  reminderPriorityThreshold?: TaskPriority
  reminderDefaultLeadMin?: number
  reminderDefaultIntensity?: ReminderIntensity
  reminderDefaultEscalateMin?: number | null
}

export interface SyncNowResult {
  success: boolean
  message: string
  importedNewData: boolean
  preferences: SyncPreferences | null
  exportedAt?: string
}

// ─── App Preferences (tray / autostart) ───

export interface AppPreferences {
  /** Closing the window hides to the tray instead of quitting. Default true. */
  closeToTray: boolean
  /** Launch at Windows login (hidden, straight to tray). */
  openAtLogin: boolean
  /**
   * Tasks at or above this priority with a future due date get an automatic
   * reminder. Default 'high' (so high and urgent qualify).
   */
  reminderPriorityThreshold: TaskPriority
  /** Minutes before the due date an automatic reminder fires. */
  reminderDefaultLeadMin: number
  /** Starting tier for new reminders. */
  reminderDefaultIntensity: ReminderIntensity
  /** Minutes before an unacknowledged reminder climbs a rung; null = never. */
  reminderDefaultEscalateMin: number | null
}

// ─── Persistence Failures (main → renderer) ───

export type PersistenceIssueKind =
  /** A stored file did not parse. */
  | 'corrupt'
  /** A write could not be completed. */
  | 'write-failed'
  /** A path could not be reached at all — typically the sync share being offline. */
  | 'unreachable'
  /**
   * A piece of the app could not start (tray icon, global hotkey). `file` holds
   * a human-readable subject rather than a path.
   */
  | 'unavailable'

export interface PersistenceIssue {
  /** Monotonic id so a queued issue delivered twice collapses in the UI. */
  id: number
  kind: PersistenceIssueKind
  file: string
  detail: string
}

// ─── IPC Return Types ───

export interface FolderScanResult {
  folder: ScannedFolder
  fileCount: number
}

export interface PaginatedFiles {
  files: FileWithMeta[]
  total: number
}
